source 'https://rubygems.org'

gem 'rake'
gem 'foreman'
gem 'sinatra'
gem 'sinatra-contrib', :require => 'sinatra/reloader'
gem 'sinatra-activerecord'
gem 'sqlite3'
gem 'activesupport'
gem 'activerecord'
gem 'slim'
gem 'json'
gem 'sass'
gem 'compass'
gem 'coffee-script'
